### ISSUE TITLE
dataquery api "grading" metric error

### ISSUE THREAD

**Issue by rsueppel** [macrosynergy/macrosynergy#479] opened 2022-09-07 10:16 UTC
Two issues:

1. The docstring says the metric "grade" can be downloaded, while actually, it is "grading".
2. More seriously, downloading of grading fails with
DataQuery Services are functioning as expected.
Execution <class 'TypeError'> with value (exc_value):
'>' not supported between instances of 'NoneType' and 'float'
![image](https://user-images.githubusercontent.com/27678335/188853836-cf090f09-378d-40c6-91aa-9ffcaabb0324.png)

**Comment by Ksteeds** [comment] 2022-09-07 11:20
New, unexpected bug. 

The code has been designed to allow all metrics to be called, and not previously encountered any errors. Again, inclined to state that the problem is not with api.py file but will look into it when I'm back unless a fix is urgently required.

**Comment by rsueppel** [comment] 2022-09-07 11:21
This is fine to look at when you are back. Cheers

**Comment by Ksteeds** [comment] 2022-09-13 08:52
Determined the issue. Currently resolving. Should allow for a more consistent DQ performance from the api.py.

**Closed** 2022-09-14 09:00 UTC
Labels: bug
